### PR TITLE
Support for character-based primary keys

### PR DESCRIPTION
**Pull request by s0x**

### CODE REVIEW

**Comment by salain** [comment]
This is incomplete the update method need to be fixed.

**Comment by s0x** [comment]
Oh, I missed that. Though, this is not trivial since the second parameter could be a column name to look for as well. The only solution I can come up right now would be to check if that string is a column name and use it as a primary key otherwise. Any thoughts from your side about that?

**Comment by salain** [comment]
I think, if you fix the part in the update is for a single row (line ~526 to 535) as you did in the where method, would fix half of it. For the other part for batch or multi row update it should work as it is, as you have to pass an array field name and value or just the field name and the value is taken from the row being updated. But I am not 100% sure.

**Comment by s0x** [comment]
Yes, multi row update works fine without any change. The single update might become ambiguous though. Think of a table Page(slug, title, content) where slug is character-based primary:
```
// Should look for page with primary 'home'
...->update($data, 'home')
// This becomes ambiguous: (search for slug = 'title' or use 'title' as column_name)
...->update($data, 'title')
```
I would propose a fix which uses 'title' as column_name in this case. If you have such a collision you should use the following notation:
```
...->update($data, ['slug' => 'title'])
```
Does this sound reasonable?

**Comment by salain** [comment]
Well at this point, laziness kicks in big time and this is burning brain cells that I cannot spare.
For any/all where clause you can use an array or first 2 parameters so I would say to do that, because this is staring to make where clause complicated for no real gain. 

```php
$this->some_model->where('pk',$value)->get();
//or 
$this->some_model->where(['pk',$value])->get();
$this->some_model->get(['pk',$value]);
$this->some_model->update($data,['pk',$value]);

```
All of these work and if you don't want to write the pk field then use this in your model that extend MY_Model: 

```php
function pk_where($value)
{
 return array($this->primary_key,$value);
}
// usage
$this->get($this->pk_where('somethingtolookfor'));
```
I hope this helps

**Comment by s0x** [comment]
Well, this works anyhow :) My solution enables the model to be used as described in the README even if you use a character-based primary key. This is mainly for the purpose of consistency. This is why I still propose the change. If there is no good reason against my change. I'd still try to get this through

**Comment by salain** [comment]
I am not saying it is working or not. I am saying there is ways around it as it is. 
And for readability I prefer not to use the where argument in get, get_all, etc.. I use the where method and always pass the field name and value even if it is the primary key. 
But this is what works for me. 
It is not my decision to accept or reject this. 
All the best

**Comment by avenirer** [comment]
Hello, I would rather keep this in the method chaining. Using as an argument is a bit ambiguous. Personally I use it only for get() methods where I only mention the primary key as parameter. $this->some_model->get(3).

I am sorry, but I wouldn't make it more complex than it is.

**Comment by s0x** [comment]
Well, the initial reason for this PR was to use get() as you described. This is not possible at the moment in case you have a character-based primary key. Therefore $this->some_model->get('abc123') does not work which i use a lot. It's a hassle to use get([id => 'abc123']) all the time. Furthermore this leads to inconstancy in using the models, which I tried to resolve. I don't want to use the update method this way at the moment either. Though, I think consistency must be considered rather than personal usage preference.

**Pull request closed without merging**
