### PR TITLE
Order by on relationship

### PR DESCRIPTION
**Pull request by afbora**
I tried to implement `order_by` feature on relations. @avenirer, can you check and optimize code please?

**Following Sample:** Get all projects that ordered by project owner rating descending.

```
$this->projects_model->with_user("order_by:rating,desc");
```

### CODE REVIEW

**Comment by avenirer** [comment]
after reading it (and not testing it) seems ok. Will merge it and we will work from there if any errors appear?

**Comment by afbora** [comment]
I didnt get any error. I just wanted you to check it out, thanks!

**Comment by francisalfanta** [comment]
I am using the latest My_model core file. And I have this in my my_model.

```
class Crm_company_job_position_model extends MY_Model 
{    
    public $table         = 'tb_crm_company_job_position';
    public $primary_key   = 'tb_crm_company_job_position_id';

    public function __construct()
    {   
        parent::__construct();     
       $this->has_many['group']    = array('Crm_group_model','tb_crm_group_id','mm_tb_crm_group_id');
    }
}

```

In my controller...

```
 $query_job_description = $this->crm_company_job_position_model
                                          ->with_group("order_by:group_name, desc")->with_company('fields:company_name')
                                         ->get_all();
```

Result:

```
Severity: Notice
Message: Undefined index: group_name
Filename: core/MY_Model.php
Line Number: 1769
```

Where did I go wrong?

**Comment by avenirer** [comment]
I think that, in order to use order_by, you need to request that field

``` php
...->with_group("fields:group_name|order_by:group_name desc");
```

Also, i don't think there is a period (,) between "group_name" and "desc"...

**Pull request merged**
