### PR TITLE
show error in unkown column

### PR DESCRIPTION
**Pull request by lloricode**
i hope this will help,

### CODE REVIEW

**Comment by avenirer** [comment]
The error reporting looks like a good addition. But why the transaction. Make these changes in two PRs, as they are addressing different things.

**Comment by lloricode** [comment]
@avenirer , ok sir wait

**Comment by lloricode** [comment]
@avenirer , can we apply transaction in MY_Model? like in CI transaction?

**Comment by avenirer** [comment]
My_model extends ci_model, so it already has transaction support.

**Comment by lloricode** [comment]
@avenirer , ok sir, maybe i just use `$this->db->trans_begin();` before the insert using extended MY_Model? hmmm thanks sir @avenirer

**Comment by avenirer** [comment]
Thanks.

**Pull request merged**
