### PR TITLE
add function to remove empty value in field, also error messages

### PR DESCRIPTION
**Pull request by lloricode**
when one of the field is empty or only has a value of '' .

so remove it to insert, to get a database row value a NULL,
because my email column is unique, it will conflict if the value is ''.

also i found in line 355 , i want to use 

```
$->rules=>array(
      'table_column_name '=>array(
               'field'=>'name_input',
                'label'=>'Label',
                 'rules'=>'somerules|otherrules'
     )
)
```

we dont use `table_name` as name in `<input>`

### CODE REVIEW

**Comment by salain** [comment]
I would say removing empty fields should be done in your own observer. 
Also if your email column is unique NULL would create an error but I would say it is undesirable.

**Comment by lloricode** [comment]
@salain ,
in email, i validate only if the field is use, but when is nothing data, it will insert ang empty or '',
because email is not required in my form.

then also im using directly form insert,
in my manual CI, i set all empty or '' value field to unset,

but im using directly form insert,  so removing it is inside the core MY_Model

**Comment by avenirer** [comment]
I would have to refuse this. I don't actually agree with having validation rules that are defined differently than the way the validation rules are defined in CodeIgniter. It adds complexity where there is no need for complexity. The auto-insert and auto-update from forms is there only to ease the process. The only requirement is for the user to accept the rule of naming input field just like is named in the table.

Also, you are doing the same mistake as before... You are addressing two issues in one PR. A pull request should address only one issue.

**Comment by avenirer** [comment]
Sorry... it seems I was wrong... @lloricode you are right about the validation rules with different name for the input field. It is a good idea...

But, again, only if you do a PR only for this, I will accept it. The other issue should be in another PR. That is why I won't take a look in there... :P

**Comment by lloricode** [comment]
@avenirer , sorry sir, next time i will address my PR, 

yes sir, can i PR one more for this, because i really need this sir?

**Comment by avenirer** [comment]
I like the way you call me "sir"... :))

**Comment by lloricode** [comment]
@avenirer , ok sir, i will PR for this, with one address issue. :+1:

**Pull request closed without merging**
