### PR TITLE
skip the field if no value in inside array

### PR DESCRIPTION
**Pull request by lloricode**
i want to unset the field with no value, like ''.
because some un-required field is not set to NULL in database when no value by input from user,

it will cause an issue of duplication like email, and username.
duplication of ''.

so unset the field in array make not include in insert so column will set NULL, as default in database

i cannot unset the some fields before calling insert, because the core MY_Model in only handle the directly insert

### CODE REVIEW

**Comment by salain** [comment]
@lloricode I think you should do that in your own observer or do it differently as I don't think it is a something that should be impose has default. 

How about declaring a property (remove_empty_before_write) and only do it if it is true. Also I would do it in the _prep_before_write method in the same loop.

**Comment by lloricode** [comment]
ok sir @salain . thanks for idea

**Comment by lloricode** [comment]
@salain ,is this ok sir?

**Comment by salain** [comment]
@lloricode , I prefer young man as sir is/was my father!

I will not be able to verify further as I don't have a PC, but it does look better to me anyway ;)
Let's see what @avenirer thinks about it

**Comment by lloricode** [comment]
@salain greate thanks :100: ,thanks sir :) :+1:

**Pull request closed without merging**
